// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_vJdaY43pIyEUlymSWeKH2II2DUYU6E0',
    appId: '1:36942341468:web:cbeda1d061d8f02a920d99',
    messagingSenderId: '36942341468',
    projectId: 'expensense-b7946',
    authDomain: 'expensense-b7946.firebaseapp.com',
    storageBucket: 'expensense-b7946.firebasestorage.app',
    measurementId: 'G-H6F1ST7NP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEpXk8OC35dzK3iALu_xKnhAJjwltFwA0',
    appId: '1:36942341468:android:963f5890b9a41d82920d99',
    messagingSenderId: '36942341468',
    projectId: 'expensense-b7946',
    storageBucket: 'expensense-b7946.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO2OFWMMPksm8Z3huqG2URRY3pHzJuJOQ',
    appId: '1:36942341468:ios:74974fda0135e9c4920d99',
    messagingSenderId: '36942341468',
    projectId: 'expensense-b7946',
    storageBucket: 'expensense-b7946.firebasestorage.app',
    iosBundleId: 'com.example.expOcr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO2OFWMMPksm8Z3huqG2URRY3pHzJuJOQ',
    appId: '1:36942341468:ios:74974fda0135e9c4920d99',
    messagingSenderId: '36942341468',
    projectId: 'expensense-b7946',
    storageBucket: 'expensense-b7946.firebasestorage.app',
    iosBundleId: 'com.example.expOcr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_vJdaY43pIyEUlymSWeKH2II2DUYU6E0',
    appId: '1:36942341468:web:6ddea24d4281acef920d99',
    messagingSenderId: '36942341468',
    projectId: 'expensense-b7946',
    authDomain: 'expensense-b7946.firebaseapp.com',
    storageBucket: 'expensense-b7946.firebasestorage.app',
    measurementId: 'G-X45DT250XV',
  );
}
