const Map<String, List<String>> categoryKeywords = {
  "Food & Groceries": [
    "grocery",
    "groceries",
    "supermarket",
    "grocery",
    "supermarket",
    "market",
    "produce",
    "fruit",
    "vegetable",
    "milk",
    "bread",
    "yogurt",
    "butter",
    "eggs",
    "meat",
    "chicken",
    "beef",
    "fish",
    "snack",
    "chips",
    "rice",
    "cereal",
    "beans",
    "mustard",
    "cream",
    "tea bags",
    "coffee powder",
    "sugar",
    "salt",
    "water",
    "canned food",
    "banana",
    "apple",
    "grape",
    "orange",
    "lettuce",
    "spinach",
    "onion",
    "potato",
    "carrot",
    "yam",
    "limes",
    "parsley",
    "coupon",
    "discount",
    "offer",
    "voucher"
        "mart",
    "bazar",
    "aldi",
    "tesco",
    "aeon",
    "fairprice",
    "giant",
    "cold storage",
    "fresh market",
    "fruit",
    "vegetables",
    "milk",
    "bread",
    "rice",
    "instant noodles",
    "pantry",
    "mydin",
    "lotus",
    "big c",
    "dairy",
    "frozen",
    "grocery",
    "produce",
    "vegetable",
    "fruits",
    "banana",
    "apple",
    "orange",
    "grapes",
    "potato",
    "lettuce",
    "milk",
    "eggs",
    "bread",
    "yogurt",
    "butter",
    "meat",
    "chicken",
    "beef",
    "fish",
    "snack",
    "chips",
    "tea bags",
    "mustard",
    "cream",
    "sweet peas",
    "clif bar",
    "ajax dish",
    "rice",
    "beans",
    "cereal",
    "carrot",
    "squash",
    "blackberry",
    "onion",
    "coupon",
    "parsley",
    "limes",
    "spinach",
    "broccoli",
    "sweet potato",
    "yam",
  ],

  "Dining & Takeout": [
    "restaurant",
    "dine",
    "dining",
    "food",
    "burger",
    "pizza",
    "restaurant",
    "takeout",
    "fast food",
    "delivery",
    "dining",
    "grabfood",
    "foodpanda",
    "burger",
    "pizza",
    "pasta",
    "steak",
    "rib eye",
    "salad",
    "latte",
    "bagel",
    "muffin",
    "soup",
    "kfc",
    "mcdonald",
    "starbucks",
    "dominos",
    "subway",
    "pizzahut",
    "caesar salad",
    "cheesecake",
    "fried rice",
    "noodles",
    "dessert"
        "kfc",
    "mcdonald",
    "dominos",
    "starbucks",
    "coffee",
    "cafe",
    "foodpanda",
    "grabfood",
    "delivery",
    "takeaway",
    "chicken",
    "subway",
    "toast",
    "noodle",
    "ramen",
    "breakfast",
    "brunch",
    "sushi",
    "bubble tea",
    "kitchen",
    "steak",
    "filet mignon",
    "rib eye",
    "caesar salad",
    "baked potato",
    "latte",
    "bagel",
    "muffin",
    "burger",
    "pizza",
    "coffee",
    "cheesecake",
    "salad",
    "soup",
    "pasta",
    "takeout",
    "restaurant",
    "dine in",
    "fast food",
    "grabfood",
    "foodpanda",
    "starbucks",
    "kfc",
    "mcdonald",
    "epic steakhouse",
    "the coffee shop",
  ],

  "Transportation": [
    "uber",
    "grab",
    "ride",
    "bus",
    "taxi",
    "train",
    "mrt",
    "lrt",
    "ktm",
    "subway",
    "toll",
    "petrol",
    "fuel",
    "fuel",
    "petrol",
    "gasoline",
    "diesel",
    "toll",
    "parking",
    "taxi",
    "grab",
    "touch n go",
    "rapidkl",
    "uber",
    "lyft",
    "bus fare",
    "train fare",
    "mrt",
    "parking fee",
    "highway fee",
    "transport service"
        "diesel",
    "gasoline",
    "top up",
    "touch n go",
    "ezlink",
    "rapidkl",
    "refuel",
    "car",
    "automobile",
    "vehicle",
    "shell",
    "petronas",
    "caltex",
    "mobil",
    "fuel",
    "petrol",
    "gasoline",
    "diesel",
    "toll",
    "mrt",
    "bus",
    "grab ride",
    "touch n go",
    "parking",
    "rapidkl",
    "transport",
    "caltex",
    "shell",
    "petronas",
    "bhp",
    "uber",
    "lyft",
  ],

  "Utilities": [
    "electricity",
    "water",
    "gas",
    "wifi",
    "internet",
    "mobile",
    "telco",
    "celcom",
    "maxis",
    "digi",
    "umobile",
    "tm",
    "unifi",
    "bill",
    "electricity",
    "water bill",
    "phone bill",
    "mobile data",
    "internet",
    "broadband",
    "astro",
    "wifi",
    "unifi",
    "maxis",
    "celcom",
    "digi",
    "syabas",
    "indah water",
    "astro bill",
    "tenaga nasional",
    "utility bill",
    "tv subscription",
    "billing",
    "monthly service",
    "tng digital"
        "billing",
    "top-up",
    "postpaid",
    "prepaid",
    "energy",
    "tenaga",
    "air selangor",
    "telekom",
    "telenor",
    "data plan",
    "electricity",
    "water",
    "phone bill",
    "internet",
    "unifi",
    "maxis",
    "celcom",
    "digi",
    "indah water",
    "tenaga nasional",
    "tng digital",
    "telekom",
    "syabas",
    "astro bill",
    "utility",
    "subscription",
    "broadband",
    "wifi",
    "mobile data",
  ],

  "Housing & Rent": [
    "rent",
    "rental",
    "apartment",
    "lease",
    "condo",
    "mortgage",
    "home loan",
    "property",
    "rent",
    "lease",
    "property fee",
    "housing fee",
    "condo",
    "apartment",
    "building maintenance",
    "land tax",
    "quit rent",
    "assessment",
    "municipal",
    "city license",
    "zoning",
    "property tax",
    "business license",
    "council fee",
    "permit",
    "processing fee"
        "airbnb",
    "hostel",
    "accommodation",
    "living",
    "residence",
    "property management",
    "management fee",
    "maintenance",
    "real estate",
    "unit",
    "rent",
    "lease",
    "property fee",
    "maintenance fee",
    "housing",
    "apartment",
    "condo",
    "land tax",
    "assessment",
    "quit rent",
    "building fee",
    "city license",
    "business license",
    "zoning review",
    "permit",
  ],

  "Health & Personal Care": [
    "advil",
    "vitamin",
    "pharmacy",
    "clinic",
    "hospital",
    "toothpaste",
    "shampoo",
    "personal care",
    "healthcare",
    "guardian",
    "advil",
    "vitamin",
    "pharmacy",
    "clinic",
    "hospital",
    "medication",
    "prescription",
    "pain relief",
    "guardian",
    "watsons",
    "caring pharmacy",
    "walgreens",
    "cvs",
    "soap",
    "shampoo",
    "toothpaste",
    "personal care",
    "healthcare",
    "hygiene",
    "sanitizer",
    "mask",
    "disinfectant",
    "first aid",
    "health product",
    "painkiller"
        "watsons",
    "caring pharmacy",
    "medication",
    "pain relief",
    "prescription",
    "durex",
    "soap",
    "detergent",
    "ajax",
    "dish liquid",
    "dish soap"
        "pharmacy",
    "clinic",
    "hospital",
    "doctor",
    "dentist",
    "medicine",
    "health",
    "fitness",
    "wellness",
    "guardian",
    "watsons",
    "prescription",
    "supplement",
    "drug",
    "vitamin",
    "test",
    "blood",
    "mask",
    "sanitizer",
    "healthcare",
    "vaccination",
    "meds",
    "shower gel",
    "toothpaste",
    "shampoo",
  ],

  "Entertainment & Subscriptions": [
    "netflix",
    "spotify",
    "youtube",
    "premium",
    "apple music",
    "hbo",
    "amazon prime",
    "cinema",
    "movie",
    "ticket",
    "event",
    "concert",
    "game",
    "psn",
    "xbox",
    "netflix",
    "spotify",
    "disney+",
    "youtube premium",
    "apple music",
    "iflix",
    "twitch",
    "movie ticket",
    "cinema",
    "concert",
    "theater",
    "streaming",
    "entertainment",
    "subscription",
    "music",
    "membership",
    "gaming",
    "premium service",
    "app subscription",
    "tv subscription"
        "steam",
    "tv",
    "theatre",
    "entertainment",
    "disney+",
    "hotstar",
    "book",
    "kindle",
    "ebook",
    "nintendo",
    "playstation",
    "netflix",
    "spotify",
    "disney+",
    "youtube premium",
    "astro",
    "iflix",
    "apple music",
    "gaming",
    "subscription",
    "entertainment",
    "movie",
    "cinema",
    "theater",
    "music",
    "concert",
    "premium membership",
    "app subscription",
  ],

  "Shopping & Miscellaneous": [
    "shopee",
    "lazada",
    "ikea",
    "uniqlo",
    "mr diy",
    "decathlon",
    "mall purchase",
    "furniture",
    "clothing",
    "sports item",
    "gadget",
    "electronic",
    "hardware",
    "shopee",
    "lazada",
    "ikea",
    "uniqlo",
    "decathlon",
    "amazon",
    "zalora",
    "sports direct",
    "mr diy",
    "shopping",
    "electronics",
    "furniture",
    "gadget",
    "hardware",
    "clothing",
    "mall",
    "purchase",
    "stationery",
    "miscellaneous",
    "sporting goods",
    "household item",
    "accessories",
    "kitchenware",
    "appliance"
        "stationery",
    "grocery bag",
    "shopping bag",
    "miscellaneous"
        "shop",
    "store",
    "mall",
    "shopee",
    "lazada",
    "amazon",
    "clothes",
    "fashion",
    "gift",
    "accessories",
    "uniqlo",
    "zalora",
    "electronic",
    "device",
    "home",
    "household",
    "hardware",
    "decoration",
    "purchase",
    "item",
    "appliance",
    "bookstore",
    "daiso",
    "muji",
    "watsons",
    "toys",
    "shopping",
    "bundle",
    "shaver",
    "bag",
    "wallet",
    "watch",
    "jewelry",
  ],
};

const Map<String, String> merchantToCategory = {
  "tesco": "Food & Groceries",
  "grabfood": "Dining & Takeout",
  "shell": "Transportation",
};
