const Map<String, List<String>> categoryKeywords = {
  "Food & Groceries": [
    "grocery",
    "groceries",
    "supermarket",
    "mart",
    "bazar",
    "aldi",
    "tesco",
    "aeon",
    "fairprice",
    "giant",
    "cold storage",
    "fresh market",
    "fruit",
    "vegetables",
    "milk",
    "bread",
    "rice",
    "instant noodles",
    "pantry",
    "mydin",
    "lotus",
    "big c",
    "dairy",
    "frozen",
  ],

  "Dining & Takeout": [
    "restaurant",
    "dine",
    "dining",
    "food",
    "burger",
    "pizza",
    "kfc",
    "mcdonald",
    "dominos",
    "starbucks",
    "coffee",
    "cafe",
    "foodpanda",
    "grabfood",
    "delivery",
    "takeaway",
    "chicken",
    "subway",
    "toast",
    "noodle",
    "ramen",
    "breakfast",
    "brunch",
    "sushi",
    "bubble tea",
    "kitchen",
  ],

  "Transportation": [
    "uber",
    "grab",
    "ride",
    "bus",
    "taxi",
    "train",
    "mrt",
    "lrt",
    "ktm",
    "subway",
    "toll",
    "petrol",
    "fuel",
    "diesel",
    "gasoline",
    "top up",
    "touch n go",
    "ezlink",
    "rapidkl",
    "refuel",
    "car",
    "automobile",
    "vehicle",
    "shell",
    "petronas",
    "caltex",
    "mobil",
  ],

  "Utilities": [
    "electricity",
    "water",
    "gas",
    "wifi",
    "internet",
    "mobile",
    "telco",
    "celcom",
    "maxis",
    "digi",
    "umobile",
    "tm",
    "unifi",
    "bill",
    "billing",
    "top-up",
    "postpaid",
    "prepaid",
    "energy",
    "tenaga",
    "air selangor",
    "telekom",
    "telenor",
    "data plan",
  ],

  "Housing & Rent": [
    "rent",
    "rental",
    "apartment",
    "lease",
    "condo",
    "mortgage",
    "home loan",
    "property",
    "airbnb",
    "hostel",
    "accommodation",
    "living",
    "residence",
    "property management",
    "management fee",
    "maintenance",
    "real estate",
    "unit",
  ],

  "Health & Personal Care": [
    "pharmacy",
    "clinic",
    "hospital",
    "doctor",
    "dentist",
    "medicine",
    "health",
    "fitness",
    "wellness",
    "guardian",
    "watsons",
    "prescription",
    "supplement",
    "drug",
    "vitamin",
    "test",
    "blood",
    "mask",
    "sanitizer",
    "healthcare",
    "vaccination",
    "meds",
    "shower gel",
    "toothpaste",
    "shampoo",
  ],

  "Entertainment & Subscriptions": [
    "netflix",
    "spotify",
    "youtube",
    "premium",
    "apple music",
    "hbo",
    "amazon prime",
    "cinema",
    "movie",
    "ticket",
    "event",
    "concert",
    "game",
    "psn",
    "xbox",
    "steam",
    "tv",
    "theatre",
    "entertainment",
    "disney+",
    "hotstar",
    "book",
    "kindle",
    "ebook",
    "nintendo",
    "playstation",
  ],

  "Shopping & Miscellaneous": [
    "shop",
    "store",
    "mall",
    "shopee",
    "lazada",
    "amazon",
    "clothes",
    "fashion",
    "gift",
    "accessories",
    "uniqlo",
    "zalora",
    "electronic",
    "device",
    "home",
    "household",
    "hardware",
    "decoration",
    "purchase",
    "item",
    "appliance",
    "bookstore",
    "daiso",
    "muji",
    "watsons",
    "toys",
    "shopping",
    "bundle",
    "shaver",
    "bag",
    "wallet",
    "watch",
    "jewelry",
  ],
};

const Map<String, String> merchantToCategory = {
  "tesco": "Food & Groceries",
  "grabfood": "Dining & Takeout",
  "shell": "Transportation",
};
